name: Scrape latest ISSUE data (daily)

on: [pull_request]
    
    # schedule:
    #     - cron: "50 21 * * *"

jobs:
    collect-issues:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              id: all-repos
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const owner = context.repo.owner;
                    const repos = await github.rest.repos.listForUser({
                        username: owner,
                    });
                    const filteredRepos = (repos) => repos
                                                        .filter((repo) => repo.has_issues && repo.has_issues === true) // check if repo has property `has_issues` before checking it's value
                                                        .map((repo) => repo.name);
                    console.log(filteredRepos);
                    return filteredRepos;
            - uses: actions/github-script@v6
              id: all-issues
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    console.log(${{steps.all-repos.outputs.result}});