name: Scrape latest ISSUE data (daily)

on: [pull_request]
    
    # schedule:
    #     - cron: "50 21 * * *"

jobs:
    collect-issues:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              id: all-repos
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const owner = context.repo.owner;
                    const repoResponse = await github.rest.repos.listForUser({
                        username: owner,
                    });
                    const filteredRepos = (r) => r
                                                    .filter((repo) => repo.has_issues)
                                                    .map((repo) => repo.name);
                    return filteredRepos(repoResponse.data);
            - uses: actions/github-script@v6
              id: all-issues
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    var allIssues: [string];
                    const repos = ${{steps.all-repos.outputs.result}};
                    for (const repo of repos) {
                        const issueResponse = await github.rest.issues.listForRepo({
                            owner,
                            repo
                        });
                        for (const issue of issueResponse.data) {
                            if (issue.pull_request) {
                                continue
                            }
                            console.log(issue);
                            # allIssues.push(issue.)
                        }
                    }