name: Scrape latest ISSUE data (daily)

on: [pull_request]
    
    # schedule:
    #     - cron: "50 21 * * *"

jobs:
    collect-issues:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              id: all-issues
              with:
                  script: |
                        const owner = context.repo.owner;
                        const repoOpts = github.rest.repos.listForUser({
                            owner,
                            "test",
                        });
                        const repos = await github.paginate(repoOpts);
                        console.log(repos);
