name: Scrape latest ISSUE data (daily)

on: [pull_request]
    
    # schedule:
    #     - cron: "50 21 * * *"

jobs:
    collect-issues:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v5
              id: all-repos
              with:
                script: |
                    const owner = context.repo.owner;
                    const repoOpts = github.rest.repos.listForUser({
                        owner,
                    });
                    const repos = await github.paginate(repoOpts);
                    return repos;
            - uses: actions/github-script@v5
              id: all-issues
              with:
                script: |
                    const repos = steps.all-repos.outputs.result;
                    console.log(repos);